snowflake:
  sfDatabase: "ETL_DATA"
  sfSchema: "ETL_SCHEMA"
  sfWarehouse: "ETL_WAREHOUSE"
  sfUrl: "DEMO"  # demo url Adjusted to the correct region (Asia Pacific - Mumbai)
  sfAccount: "DEMO"  # Added account ID
  sfUser: "demo"
  sfPassword: "demo"
  sfRole: "ACCOUNTADMIN"  # Optional, if needed

dataframes:
  customer: 
  review: 
  product: 
  orders: 
  order_item: 

unique_keys:
  customer: "customer_id"
  review: "review_id"
  product: "product_id"
  orders: "order_id"
  order_item: "order_item_id"
