version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
    ports:
      - "8080:8080" 
      - "7077:7077" 
      - "8888:8888" 
    networks:
      - spark-network
    volumes:
      - spark-data:/spark-data

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network
    depends_on:
      - spark-master
    volumes:
      - spark-data:/spark-data

networks:
  spark-network:
    driver: bridge

volumes:
  spark-data: